version: '3'
services:

  server:
    build: .
    image: dora
    command: server

    ports:
      - "8000:8000"

    volumes:
      - ./dora-simple.yaml:/etc/bmc-toolbox/dora.yaml:ro
      # For /tmp/dora.db
      - /tmp:/tmp

  dora:
    build: .
    image: dora

    volumes:
      - ./dora-simple.yaml:/etc/bmc-toolbox/dora.yaml:ro
      # To get a list of networks with BMCs
      - ./kea-simple.conf:/etc/kea/kea.conf:ro
      # For /tmp/dora.db
      - /tmp:/tmp
